### ISSUE TITLE
[Bug]: setting page disappears

### ISSUE THREAD

**Issue by WanQiyang** [frontend-engineering/Invio#11]
### What happened?

I installed Invio in the official community plugin list, but the setting page does not appear after enabling the plugin. Is it a bug? The plugin version is 0.7.6 and Obsidian version is 1.4.16 on Windows 11. Thank you for your efforts!

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.7.6

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sqkkyzx** [comment]
遇到了同样的问题，回退到了 `0.7.5` ，并使用 CDN 提供的重定向规则让错误的反斜杠能够正常工作。

**Comment by walkthunder** [comment]
Shoule be fixed in the latest version @sqkkyzx  @WanQiyang

**Comment by WanQiyang** [comment]
> Shoule be fixed in the latest version @sqkkyzx @WanQiyang

Confirmed. It has been fixed in 0.7.23. Thank you!
