### ISSUE TITLE
[Bug]: Action Folder publish Error

### ISSUE THREAD

**Issue by cumany** [frontend-engineering/Invio#6]
### What happened?

Thanks for the great plugin.
I have successfully set up Alibaba Cloud OSS and can synchronize files without any issues. However, when I try to execute the "Publish Folder" command, it shows an absolute folder error and fails to publish. I'm not sure where the problem is, could you please help me take a look? Thank you.

![image](https://github.com/frontend-engineering/Invio/assets/42957010/5024191b-7c4d-4786-bb7a-19f4837c44d4)

### What OS are you using?

Windows

### What remote cloud services are you using?

others

### Version of the plugin

0.6.5

### Version of Obsidian

1.4.14

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by cumany** [comment]
This is the error message from the console
![image](https://github.com/frontend-engineering/Invio/assets/42957010/2e120b3f-dd08-4176-9c3e-910ba142b15c)

**Comment by walkthunder** [comment]
Fixing Windows path compatibility issues. The issue will be resolved in a couple of days.

**Comment by walkthunder** [comment]
Update to Invio version 0.7.0 and retry. The Windows platform should function properly. @cumany

**Comment by cumany** [comment]
我更新到了0.7.3版本，但当我开启插件的时候 控制台出现了错误。
另外我在工作目录的右键菜单中找不到了  发布文件夹的选项了。
![image](https://github.com/frontend-engineering/Invio/assets/42957010/682c9665-d2a4-45c6-81c3-368a4f48d5f3)

**Comment by cumany** [comment]
Thank you! I can pubulish files through the Force Mode option in the Command Panel!
